name: Node Integration Test

on: 
  push:
    paths:
    - 'backend/**'
    - '.github/workflows/node-backend.yml'


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node 22.16.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'

      - name: Install dependencies
        run: npm install

      - name: Test with Jest
        run: npm test
