name: Update sleeper_players table on a CRON Schedule

on:
  Schedule:
   - CRON: "*/5 * * * *"
  #  "0 0 * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: ./backend/database_scripts
      run : | 
        python -m pip install --upgrade pip
        pip install requests pymongo dotenv
    - name: Sleeper Players script
      working-directory: ./backend/database_scripts
      run: |
        python insert_name_players.py
